<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <ProjectReference Include="../../src/ComputerArchitecture.Mano/ComputerArchitecture.Mano.csproj" />
    <ProjectReference Include="../../src/ComputerArchitecture.Mano.Cli/ComputerArchitecture.Mano.Cli.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
